---
# defaults file for wordpress-docker
compose_project_dir: /efs/{{ system_user }}/compose-pi
telegraf_config_dir: /efs/{{ system_user}}/telegraf
telegraf_config_file: "{{telegraf_config_dir}}/telegraf.conf"
domain: pi.smartdevops.net
stage: production
telegrafuserpass: "{{  (telegraf_pass.stdout | from_json).SecretString }}"
influxadminpass: "{{  (influxadmin_pass.stdout | from_json).SecretString }}"
