---
# defaults file for wordpress-docker
compose_project_dir: /efs/{{ system_user }}/compose-pi
telegraf_config_file: /efs/{{ system_user}}/telegraf/telegraf.conf
domain: pi.smartdevops.net
stage: production
telegrafuserpass: "{{  (telegrafpass.stdout | from_json).SecretString }}"
influxadminpass: "{{  (influxadminpass.stdout | from_json).SecretString }}"
