---
- name: upgrade all packages
  package:
    name: "*"
    state: latest
  become: yes

- name: be sure ntp is installed
  package:
    name: ntp
    state: present
  tags: ntp
  become: yes

- name: be sure ntp is configured
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp
  tags: ntp
  become: yes

- name: be sure ntp is running and enabled
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp
  become: yes

- name: Get EFS ID
  command: aws secretsmanager get-secret-value --region af-south-1 --output json --secret-id efsid
  register: efsid

- name: Get InfluxDB Admin Password
  command: aws secretsmanager get-secret-value --region af-south-1 --output json --secret-id influxadminpass
  register: influxadmin_pass

- name: Get Telegraf User Password
  command: aws secretsmanager get-secret-value --region af-south-1 --output json --secret-id telegrafpass
  register: telegraf_pass
